## Numpy

Numpy examples courteousy of: http://scipy-lectures.org/intro/numpy/array_object.html#numpy-arrays

In [1]:
import numpy as np

## Numpy Arrays

1D Array

In [2]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

2D Array

In [3]:
b = np.array([[0, 1, 2], [3, 4, 5]]) # 2 x 3 array
b

array([[0, 1, 2],
       [3, 4, 5]])

3D Array

In [4]:
c = np.array([[[1], [2]], [[3], [4]]])
c

array([[[1],
        [2]],

       [[3],
        [4]]])

### Why do we care about numpy? It's fast!

In [5]:
a = np.arange(10)

In [6]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Useful Methods for creating common Arrays

Create an Array of Zeros

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Create an array of Ones

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Identity Matrix

In [11]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])