# Numpy Indexing & Slicing

In [1]:
import numpy as np

#### Indexing and Slicing

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a[1]

1

In [4]:
a[9]

9

In [5]:
a[:3] # First three indicies

array([0, 1, 2])

In [6]:
# slice indicies 1 to 3
a[1:3]

array([1, 2])

In [7]:
a[-2:]

array([8, 9])

#### Multidimensional arrays

In [8]:
a = np.diag(np.arange(3))
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [9]:
a[2, 1] = 10 # third line, second column
a

array([[ 0,  0,  0],
       [ 0,  1,  0],
       [ 0, 10,  2]])

### Pair Programming

Write code that will slice the numpy array below to select values of a single color. Before doing so, what will the desired shape of the resulting array be?

![Scipy-Lectures.org](scipy_lectures.org_Slicing.png)

Image courtesy of ScipyLectures.org

In [10]:
a = np.arange(6) + np.arange(0, 51, 10)[:, np.newaxis]
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

#### 1. Green

#### 1. Blue

#### 1. Red

#### 1. Purple