In [1]:
import pandas as pd
import numpy as np

### Random Choice

https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.choice.html

In [2]:
np.random.choice(10, 5) # Sample 5 values from arange(0,10)

array([6, 2, 7, 7, 1])

### Sample without Replacement

In [3]:
np.random.choice(10, 5) # Sample 5 values from arange(0,10)

array([9, 9, 3, 5, 1])

### Sample with Replacement

In [4]:
np.random.choice(3, 5, replace=True)

array([0, 0, 0, 2, 0])

### Categorical variables

In [5]:
characters_list = ['pooh', 'rabbit', 'piglet', 'Christopher']
np.random.choice(characters_list, 5)

array(['pooh', 'pooh', 'pooh', 'Christopher', 'Christopher'], dtype='<U11')

### Specifying probabilities
Default is uniform random sampling. But we can also specify probabilities

In [6]:
np.random.choice(characters_list, 5, p=[0.5, 0.1, 0.1, 0.3])

array(['pooh', 'piglet', 'Christopher', 'rabbit', 'pooh'], dtype='<U11')

## Pair Programming

1. Represent a unfairly weighted coin, with probabily of heads = 8/10.

2. Chose a favorite TV show. Create a pandas dataframe with randomly generated data. Generate 100 rows of data with 3 continuous features and 2 categorical features for your favorite TV show. 