In [1]:
import numpy as np

## Numpy ArgMin/Max & Take

In [2]:
a = np.arange(10) + 10
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [3]:
a.argmax()  # index of maximum

9

In [4]:
a[a.argmax()] # pass this 

19

### 2D arrays

In [5]:
a = np.arange(6).reshape(2,3) + 10
a

array([[10, 11, 12],
       [13, 14, 15]])

In [6]:
np.sum(a, axis=0) # sum along columns dimension
# axis you specify (rows) is reduced

array([23, 25, 27])

In [7]:
np.sum(a, axis=1)

array([33, 42])

In [8]:
index = np.unravel_index(a.argmax(), a.shape)
print(index)
a[index]

(1, 2)


15

## Take

`np.take()` documentation: https://numpy.org/doc/stable/reference/generated/numpy.take.html

In [9]:
a = np.arange(10) + 10
print(a)
indices = [0, 1, 4]
np.take(a, indices)

[10 11 12 13 14 15 16 17 18 19]


array([10, 11, 14])

In [10]:
np.take(a, a.argmin())

10

## Reshape

Expand Dimensions

In [11]:
a = np.arange(10) + 10
print(a.shape)
print(a)

(10,)
[10 11 12 13 14 15 16 17 18 19]


In [12]:
a.reshape(10,1)

array([[10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [13]:
a.reshape(5,2)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [14]:
np.expand_dims(a, axis=1)

array([[10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [15]:
c = np.arange(24) + 10
c.reshape(4,3,2)

array([[[10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21]],

       [[22, 23],
        [24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31],
        [32, 33]]])

In [16]:
np.reshape(c, (4, 3*2))

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33]])

In [17]:
c.flatten()

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33])